# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'setup-php'
description: 'Set up your GitHub Actions workflow with a specific version of PHP'
author: 'khs1994'
inputs:
  php_version:
    description: PHP version
    default: 7.4.3
  php_type:
    description: php image type, fpm | composer | swoole | php-cs-fixer | sami
    default: fpm
  job_container_network:
    description: The id of the container network. The runner creates the network used by all containers in a job
    default: bridge
runs:
  using: 'node12'
  main: 'lib/setup-php.js'
branding:
  icon: 'box'
  color: 'green'
