on:
  push:
  pull_request:

name: CI

jobs:
  test:
    name: Service Network
    runs-on: ubuntu-latest
    steps:
      - name: "Test Network"
        uses: ./
        # uses: khs1994-docker/actions-setup-php@master
        with:
          job_services_network: ${{ job.services.network }}
          args: |
            ping redis -c 4
    services:
      mysql:
        image: redis:5.0.5-alpine
